#!/bin/bash
top_dir="${TOP:=$PWD}"
clean=1
if [[ $1 = "-clean" ]] ; then
    clean=0
    shift
fi
if [[ $# -eq 0 ]] ; then
    for i in *.org; do sources+=("$i"); done
else
    sources=("$@")
fi
# User name is defined in Emacs config:
emacs_user_full_name=$(emacs --batch -Q --eval '(message user-full-name)')
# System user name
user_name=$(logname)
user_record=$(getent passwd $user_name)
user_gecos_field=$(echo "$user_record" | cut -d ':' -f 5)
user_full_name=$(echo "$user_gecos_field" | cut -d ',' -f 1)
if [[ -z "$user_full_name" ]] ; then user_full_name=$user_name ; fi
if [[ -z "$emacs_user_full_name" ]] ; then
    # Use system user name as fallback
    AUTHOR=$user_full_name
else
    # Use Emacs defined user name
    AUTHOR=$emacs_user_full_name
fi
# Loop through sources
for i in "${sources[@]}" ; do
    s=$i
    t=${i%.org}.tex
    p=${i%.org}.pdf
    h=${i%.org}.html
    d=${i%.org}.deps
    a=${i%.org}.auxdir
    if [[ $clean -eq 0 ]] ; then
        rm -rf "$t" "$p" "$h" "$d" "$a"
    else
        # missing target pdf
        # source newer than target
        # this script newer than target
        if [[ (! -e $p) || $s -nt $p || $0 -nt $p ]] ; then
            echo ">>>           $s => $p"
            emacs --batch \
                  --no-init-file --no-site-file --init-directory $top_dir/.emacs.d \
	          -l $top_dir/.emacs.d/org-mode_new-init.el \
	          --visit "$s" \
                  --eval "(setq user-full-name \"$AUTHOR\")" \
                  -f org-babel-execute-buffer \
	          -f org-latex-export-to-pdf

            # getent? logname? pinky?
            # grep user-full-name ~/.emacs ???
            # '(user-full-name "Michel Briand")
            # GITHUB_ACTOR The username of the user that triggered the workflow.
            
            # --eval "(setq user-full-name \"Defaults to username=$USER, set [#+AUTHOR: Your Name] in your document\")" \
                
        fi
        # missing target html
        # source newer that target
        # this script newer than target
        if [[ (! -e $h) || $s -nt $h || $0 -nt $h ]] ; then
            echo ">>>           $s => $h"
            emacs --batch \
                  --no-init-file --no-site-file --init-directory $top_dir//.emacs.d \
	          -l $top_dir/.emacs.d/org-mode_new-init.el \
	          --visit "$s" \
	          -f org-html-export-to-html
        fi
    fi
done
