#!/bin/bash
top_dir="${TOP:=$PWD}"
clean=1
if [[ $1 = "-clean" ]] ; then
    clean=0
    shift
fi
if [[ $# -eq 0 ]] ; then
    for i in *.org; do sources+=("$i"); done
else
    sources=("$@")
fi
for i in "${sources[@]}" ; do
    s=$i
    t=${i%.org}.tex
    p=${i%.org}.pdf
    h=${i%.org}.html
    d=${i%.org}.deps
    a=${i%.org}.auxdir
    if [[ $clean -eq 0 ]] ; then
        rm -rf "$t" "$p" "$h" "$d" "$a"
    else
        # missing target pdf
        # source newer than target
        # this script newer than target
        if [[ (! -e $p) || $s -nt $p || $0 -nt $p ]] ; then
            echo ">>>           $s => $p"
            emacs --batch \
                  --no-init-file --no-site-file --init-directory $top_dir/.emacs.d \
	          -l $top_dir/.emacs.d/org-mode_new-init.el \
	          --visit "$s" \
                  -f org-babel-execute-buffer \
	          -f org-latex-export-to-pdf
        fi
        # missing target html
        # source newer that target
        # this script newer than target
        if [[ (! -e $h) || $s -nt $h || $0 -nt $h ]] ; then
            echo ">>>           $s => $h"
            emacs --batch \
                  --no-init-file --no-site-file --init-directory $top_dir//.emacs.d \
	          -l $top_dir/.emacs.d/org-mode_new-init.el \
	          --visit "$s" \
	          -f org-html-export-to-html
        fi
    fi
done
