#!/bin/bash

me=${0##*/}
md=${0%/*}

echo $(realpath $md)

: ${ATELIER_ROOT:=$md}
: ${EMACS_ROOT:=$HOME/.emacs.d}
if [ "$GITHUB_ACTIONS" == "true" ] ; then
    echo "Running in pipeline"
else
    if [ -d "$ATELIER_ROOT/.emacs.d" ] ; then
        EMACS_ROOT=$ATELIER_ROOT/.emacs.d
    fi
fi
: ${DOCUMENTS_ROOT:=$PWD}

clean=1
if [[ $1 = "-clean" ]] ; then
    clean=0
    shift
fi

if [[ $# -eq 0 ]] ; then
    for i in *.org; do sources+=("$i"); done
else
    sources=("$@")
fi

emacs_user_full_name=$(emacs --batch -Q --eval '(princ user-full-name)')

echo "emacs_user_full_name=$emacs_user_full_name"

# If AUTHOR is set it takes precedence
: ${AUTHOR:=$GITHUB_ACTOR} # else GITHUB_ACTOR
: ${AUTHOR:=$emacs_user_full_name} # else user full name (local)

echo "AUTHOR=$AUTHOR"

function emacs_cmd {
    emacs --batch -Q \
          --init-directory $EMACS_ROOT \
	  -l $ATELIER_ROOT/lib/org-mode_new-init.el \
          --eval "(setq user-full-name \"$AUTHOR\")"
}

#type emacs_cmd

products=()

# Loop through sources
for i in "${sources[@]}" ; do
    s=$i
    t=${i%.org}.tex
    p=${i%.org}.pdf
    h=${i%.org}.html
    d=${i%.org}.deps
    a=${i%.org}.auxdir
    if [[ $clean -eq 0 ]] ; then
        rm -rf "$t" "$p" "$h" "$d" "$a"
    else
        # missing target pdf
        # source newer than target
        # this script newer than target
        if [[ (! -e $p) || $s -nt $p || $0 -nt $p ]] ; then
            echo ">>>           $s => $p"
            set -x
            emacs_cmd \
	          --visit "$s" \
                  -f org-babel-execute-buffer \
	          -f org-latex-export-to-pdf
            if [ $? -eq 0 ] ; then
                products+=("$PWD/$p")
            fi
            set +x
        fi
        # missing target html
        # source newer that target
        # this script newer than target
        if [[ (! -e $h) || $s -nt $h || $0 -nt $h ]] ; then
            echo ">>>           $s => $h"
            emacs_cmd \
	          --visit "$s" \
	          -f org-html-export-to-html
            if [ $? -eq 0 ] ; then
                products+=("$PWD/$h" "$PWD/org.css")
            fi
        fi
    fi
done

if [ "$GITHUB_ACTIONS" == "true" ] ; then
    (
        printf "products<<EOF\n"
        for i in "${products[@]}" ; do
            printf "- $i\n"
        done
        printf "EOF\n"
    ) >> "$GITHUB_ENV"
    # echo "products=${products[@]}" >> "$GITHUB_ENV"
fi
