#+LANGUAGE: fr

*** plan
création d'un conteneur pour act_runner (exécuteur gitea)
  répertoire =container/gitea-act_runner=
  fichier =compose.yml=

création d'un conteneur avec emacs pour produire les documents
création d'un pod pour mettre tout ça ensemble
création d'un service systemd pour le pod

*** TODO/bugs

**** network_mode
    network_mode: 'pasta:--ipv4-only'
    génère une erreur, depuis le conteneur on n'a plus accès au réseau/service gitea

: [runner] | time="2025-11-21T14:48:55Z" level=error msg="fail to invoke Declare" error="unavailable: dial tcp 82.64.192.201:3000: connect: connection refused"

avec network_mode: 'host', ça marche

**** git clone dans le conteneur exécutant le job

fatal: unable to access 'https://kheb.ignorelist.com:3000/publius/atelier_sciences/': Could
not resolve host: kheb.ignorelist.com

**** adresser le conteneur emacs

port?


*** stratégie locale

Pourquoi passer par le réseau (compliqué) alors qu'on est censé
exécuter un runner sur le même serveur (dans ce cas simple). Ne
pourrait-on pas monter le répertoire des dépôts dans le job runner ?

créons un conteneur qui utilise le répertoire local de gitea
et le monte (via services)

: podman run -it --name testgitlocal -v /var/lib/gitea/data/gitea-repositories:/repos:ro fb5e48a0afc7 /bin/bash

dans le conteneur :

: git clone /repos/publius/atelier_sciences.git

ça fonctionne :) !



* Atelier Sciences

Options de départ :

 - overleaf
 - cocalc
 - gitea
 - michel package :)

* Mes idées (michel package)

templace org

git (gitea | gitlab | github) + Emacs + org + latex + [Makefile|gitlab-ci] => pdf, html ...

bib !

export slides beamer ou slides JS

Un truc simple ! Pas *-reveal !

* Besoin

interface web 
 - custom? NON
 - overleaf? NON
 - gitea? SIMPLE OUI
 - 

fabrication locale
 - emacs + C-c C-e
 - script ou Makefile

fabrication serveur GdC
 - runner

* Implémentation

** idée d'implémentation

gitea : podman + act_runner
Makefile

*** runner

création d'un secret avec podman :

: echo 'montoken' | podman secret create atelier_sciences_runner_token -

#+begin_src shell
  podman run \
         -e GITEA_INSTANCE_URL=https://https://kheb.ignorelist.com:3000 \
         -e GITEA_RUNNER_REGISTRATION_TOKEN=$my_token \
         -v /var/run/docker.sock:/var/run/docker.sock \
         --name r_atelier_sciences \
         docker.io/gitea/act_runner:latest
#+end_src

#+begin_src yaml
name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
#+end_src
